# Generated by Django 3.1.3 on 2021-05-29 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_auto_20210530_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='marked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizz.choice'),
        ),
    ]
