# Generated by Django 3.1.3 on 2021-06-01 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_attendee_marked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='deptstud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizz.department'),
        ),
    ]
